# Generated by Django 4.0.6 on 2022-07-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CST_users', '0002_alter_userprofile_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
