# Generated by Django 4.0.6 on 2022-07-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('post_id', models.UUIDField(default='4a3fdf9f-7f06-48fd-ade5-4dafa54ef180', editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
