# Generated by Django 4.0.6 on 2022-07-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CST_cms', '0004_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
