# Generated by Django 4.0.6 on 2022-07-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CST_cms', '0005_post_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
