# Generated by Django 4.0.6 on 2022-07-08 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CST_users', '0004_remove_userprofile_username'),
        ('CST_cms', '0011_remove_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CST_users.userprofile'),
        ),
    ]
